services:
 - docker
install:
  - docker build -t unifi .
  - docker run -d -p 127.0.0.1:8443:8443 --name unifi unifi 
script:
  - docker ps | grep -q unifi
  - sleep 10 && curl -k -L --fail https://127.0.0.1:8443 || exit 1
